from episode_creator_for_data_generation import run_episode_creator

def main():
    file_path = ""
    file_name = "insert_contest_data.sql"

    with open(file_path + file_name, 'w') as file:
        file.write('-- SQL commands generated by contest_creator\n')

    for _ in range(100):
        try:
            episode = run_episode_creator(file_path, file_name)
            if episode == 1:
                print("ERROR: Contest creation stopped")
                break
        except Exception as e:
            print(f"An error occurred during episode creation: {e}")

if __name__ == '__main__':
    main()
